import 'package:flutter/material.dart';

final ThemeData lbThemeLight = ThemeData(
  primarySwatch: const MaterialColor(4292371808, {
    50: Color(0xfffaebeb),
    100: Color(0xfff5d7d6),
    200: Color(0xffebb0ad),
    300: Color(0xffe18884),
    400: Color(0xffd7605b),
    500: Color(0xffcd3932),
    600: Color(0xffa42d28),
    700: Color(0xff7b221e),
    800: Color(0xff521714),
    900: Color(0xff290b0a)
  }),
  brightness: Brightness.light,
  primaryColor: const Color(0xffd86560),
  primaryColorBrightness: Brightness.dark,
  primaryColorLight: const Color(0xfff5d7d6),
  primaryColorDark: const Color(0xff7b221e),
  canvasColor: const Color(0xfffafafa),
  scaffoldBackgroundColor: const Color(0xfffafafa),
  bottomAppBarColor: const Color(0xffffffff),
  appBarTheme: const AppBarTheme(elevation: 0),
  cardColor: const Color(0xffffffff),
  dividerColor: const Color(0x1f000000),
  highlightColor: const Color(0x66bcbcbc),
  splashColor: const Color(0x66c8c8c8),
  selectedRowColor: const Color(0xfff5f5f5),
  unselectedWidgetColor: const Color(0x8a000000),
  disabledColor: const Color(0x61000000),
  toggleableActiveColor: const Color(0xffa42d28),
  secondaryHeaderColor: const Color(0xfffaebeb),
  backgroundColor: const Color(0xffebb0ad),
  dialogBackgroundColor: const Color(0xffffffff),
  indicatorColor: const Color(0xffcd3932),
  hintColor: const Color(0x8a000000),
  errorColor: const Color(0xffd32f2f),
  buttonTheme: const ButtonThemeData(
    textTheme: ButtonTextTheme.normal,
    minWidth: 88,
    height: 36,
    padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
    shape: RoundedRectangleBorder(
      side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      ),
      borderRadius: BorderRadius.all(Radius.circular(2.0)),
    ),
    alignedDropdown: false,
    buttonColor: const Color(0xffe0e0e0),
    disabledColor: const Color(0x61000000),
    highlightColor: const Color(0x29000000),
    splashColor: const Color(0x1f000000),
    focusColor: const Color(0x1f000000),
    hoverColor: const Color(0x0a000000),
    colorScheme: ColorScheme(
      primary: Color(0xffd86560),
      primaryVariant: Color(0xff7b221e),
      secondary: Color(0xffcd3932),
      secondaryVariant: Color(0xff7b221e),
      surface: Color(0xffffffff),
      background: Color(0xffebb0ad),
      error: const Color(0xffd32f2f),
      onPrimary: Color(0xffffffff),
      onSecondary: Color(0xffffffff),
      onSurface: Color(0xff000000),
      onBackground: Color(0xffffffff),
      onError: const Color(0xffffffff),
      brightness: Brightness.light,
    ),
  ),
  inputDecorationTheme: InputDecorationTheme(
    labelStyle: TextStyle(
      color: const Color(0xdd000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    helperStyle: TextStyle(
      color: const Color(0xdd000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    hintStyle: TextStyle(
      color: const Color(0xdd000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    errorStyle: TextStyle(
      color: const Color(0xdd000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    errorMaxLines: null,
    isDense: false,
    contentPadding: EdgeInsets.only(top: 12, bottom: 12, left: 0, right: 0),
    isCollapsed: false,
    prefixStyle: TextStyle(
      color: const Color(0xdd000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    suffixStyle: TextStyle(
      color: const Color(0xdd000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    counterStyle: TextStyle(
      color: const Color(0xdd000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    filled: false,
    fillColor: const Color(0x00000000),
    // errorBorder: UnderlineInputBorder(
    //   borderSide: BorderSide(
    //     color: const Color(0xff000000),
    //     width: 1,
    //     style: BorderStyle.solid,
    //   ),
    //   borderRadius: BorderRadius.all(Radius.circular(4.0)),
    // ),
    focusedBorder: UnderlineInputBorder(
      borderSide: BorderSide(
        color: const Color(0xff000000),
        width: 1,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    // focusedErrorBorder: UnderlineInputBorder(
    //   borderSide: BorderSide(
    //     color: const Color(0xff000000),
    //     width: 1,
    //     style: BorderStyle.solid,
    //   ),
    //   borderRadius: BorderRadius.all(Radius.circular(4.0)),
    // ),
    // disabledBorder: UnderlineInputBorder(
    //   borderSide: BorderSide(
    //     color: const Color(0xff000000),
    //     width: 1,
    //     style: BorderStyle.solid,
    //   ),
    //   borderRadius: BorderRadius.all(Radius.circular(4.0)),
    // ),
    // enabledBorder: UnderlineInputBorder(
    //   borderSide: BorderSide(
    //     color: const Color(0xff000000),
    //     width: 1,
    //     style: BorderStyle.solid,
    //   ),
    //   borderRadius: BorderRadius.all(Radius.circular(4.0)),
    // ),
    // border: UnderlineInputBorder(
    //   borderSide: BorderSide(
    //     color: const Color(0xff000000),
    //     width: 1,
    //     style: BorderStyle.solid,
    //   ),
    //   borderRadius: BorderRadius.all(Radius.circular(4.0)),
    // ),
  ),
  iconTheme: IconThemeData(
    color: const Color(0xdd000000),
    opacity: 1,
    size: 24,
  ),
  primaryIconTheme: IconThemeData(
    color: const Color(0xffffffff),
    opacity: 1,
    size: 24,
  ),
  sliderTheme: SliderThemeData(
    activeTrackColor: null,
    inactiveTrackColor: null,
    disabledActiveTrackColor: null,
    disabledInactiveTrackColor: null,
    activeTickMarkColor: null,
    inactiveTickMarkColor: null,
    disabledActiveTickMarkColor: null,
    disabledInactiveTickMarkColor: null,
    thumbColor: null,
    disabledThumbColor: null,
    overlayColor: null,
    valueIndicatorColor: null,
    showValueIndicator: null,
    valueIndicatorTextStyle: TextStyle(
      color: const Color(0xffffffff),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
  ),
  tabBarTheme: TabBarTheme(
    indicatorSize: TabBarIndicatorSize.tab,
    labelColor: const Color(0xffffffff),
    unselectedLabelColor: const Color(0xb2ffffff),
  ),
  chipTheme: ChipThemeData(
    backgroundColor: const Color(0x1f000000),
    brightness: Brightness.light,
    deleteIconColor: const Color(0xde000000),
    disabledColor: const Color(0x0c000000),
    labelPadding: EdgeInsets.only(top: 0, bottom: 0, left: 8, right: 8),
    labelStyle: TextStyle(
      color: const Color(0xde000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    padding: EdgeInsets.only(top: 4, bottom: 4, left: 4, right: 4),
    secondaryLabelStyle: TextStyle(
      color: const Color(0x3d000000),
      fontSize: null,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    secondarySelectedColor: const Color(0x3dd86560),
    selectedColor: const Color(0x3d000000),
    shape: StadiumBorder(
        side: BorderSide(
      color: const Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    )),
  ),
  dialogTheme: DialogTheme(
      shape: RoundedRectangleBorder(
    side: BorderSide(
      color: const Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    ),
    borderRadius: BorderRadius.all(Radius.circular(0.0)),
  )),
);
