name: losbetosapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # algolia: 1.0.0
  # flutter_native_splash: ^1.2.0
  google_fonts: ^2.1.0
  url_strategy: ^0.2.0
  regex_router: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  firebase_core: "^1.7.0"
  firebase_auth: "^3.1.3"
  cloud_firestore: ^2.5.1
  provider:
  google_sign_in:
  flavor_ui:
    path: ../../../flavor/flavor_ui
  flavor_auth:
    path: ../../../flavor/flavor_auth
  flavor_redis:
    path: ../../../flavor/flavor_redis
  flavor_http:
    path: ../../../flavor/flavor_http

  cloud_functions: "^3.0.4"
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.0-dev.11
  miniplayer: ^1.0.0+2
  timeago: ^3.0.2
  flutter_remix: ^0.0.3
  im_stepper: ^0.1.3
  flutter_svg: ^0.23.0+1
  flex_color_scheme: ^3.0.1
  stripe: ^4.5.0
  credit_card_validator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/logos/
    - assets/icons/
